---
title: "R Notebook"
output: html_notebook
---

This is the R notebook for miRNA analysis in IBD book chapter

Prerequisites:
The following packages are needed to be installed to follow this workflow:
gprofiler
tydiverse


The first step is accesing the miRNA-target interactions from the various databases. For this workflow we will use mirtarbase, targetScan and Mirwalk.
Targetscan: http://www.targetscan.org/cgi-bin/targetscan/data_download.vert72.cgi
mirtarbase: https://mirtarbase.cuhk.edu.cn/~miRTarBase/miRTarBase_2019/php/download.php


```{r}

```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
